language: generic
services:
  - docker

before_install:
  - docker build  -t zaden/docker-reactapp -f Dockerfile.dev .

script:
  - docker run -e CI=true zaden/docker-reactapp yarn run test -- --coverage