language: generic
services:
  - docker

before_install:
  - docker build  -t zaden/docker-reactapp -f Dockerfile.dev .

script:
  - docker run -e CI=true zaden/docker-reactapp yarn run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-reactapp
  env: DockerReactapp-env
  bucket_name: elasticbeanstalk-us-east-2-406033701411
  bucket_path: docker-reactapp
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


